#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
# Load global styles, colors and icons
source "$CONFIG_DIR/globalstyles.sh"

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker
sketchybar --bar "${bar[@]}" --default "${item_defaults[@]}"

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/mail.sh
source $ITEM_DIR/github.sh
source $ITEM_DIR/stats.sh
source $ITEM_DIR/media.sh

# Brackets
# Brackets '/space\..*/'
sketchybar --add bracket left.side '/space\..*/' \
  --set left.side "${bracket_defaults[@]}" \
  --add bracket status_icons date clock battery clock \
  --set status_icons "${bracket_defaults[@]}"
# --add bracket notifications "LemonMonitor,Item-0" "Control Center,WiFi" \
# --set notifications "${bracket_defaults[@]}"

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --hotload on
sketchybar --update
